- name: deploying conatiner
  hosts: ans-host
  #become: true
  
  tasks:
      - name: Remove unused image
        shell: docker image prune -f
       
      - name: create a new tomcat container using the defined Dockerfile
        shell: docker run -d --name tomcat-container -p 8080:8080 aakashraj47/bsafe
